Twink Link Req_01
Spikeone/WoWAddons pull request #3
Opened 2020-04-13 11:38 UTC by Zirafinu

Hi Spike,
ich hab endlich die Zeit gefunden mal ein paar Zeilen zu schreiben.
Der eingeloggte Char wird genau so gelinkt wie bisher.
Twinks können gelink werden, indem Sie in der Datenbank/Liste mit gedrückter Umschalt Taste angeclickt werden.
Der twink link sieht dann so aus:
"|Hitem:1:1:0:0:0:"<Version>":0:"<Linkender Character Encodiert>"|h["<character name>"]|h|r"

Das <Linkender Character Encodiert> bildet den Namen in dezimal ab("%03d" für jedes byte/zeichen).

In der Datenbank wird ein Feld "IS_OWN" gepflegt, das auf '1' gesetzt wird, wenn ein Charlink für den aktuellen char gespeichert wird.

Für den aktuellen char werden die Daten in der Datenbank aktualisiert, sobald sich die Talente oder das Inventar ändert. Ich hätte gerne nur bei logout die Daten aktualisiert, aber da habe ich nur noch einen nakten char gesehen.

Grüße Zirafinu

2020-04-13 22:33 UTC, Spikeone requested changes
Könntest das nochmal ansehen? :)

2020-04-13 22:33 UTC, Spikeone commented on SpikesCharLink/SpikesCharLink.lua
> +function StringToDecString(text)
Muss die global sein? sollte sonst mit function local auch gehen oder? Bin mir da aber auch nicht 100% sicher

2020-04-13 22:33 UTC, Spikeone commented on SpikesCharLink/SpikesCharLink.lua
> +            SendAddonMessage("SCLLV", SCL_CONSTS.VERSION, "WHISPER", wisperTarget);
bitte "whisperTarget" :)

2020-04-13 22:33 UTC, Spikeone commented on SpikesCharLink/SpikesCharLink.lua
> +        local player, equipHash = SCL_SerializePlayer()
wozu in lokale variablen die danach dann nicht mehr genutzt werden?

2020-04-13 22:33 UTC, Spikeone commented on SpikesCharLink/SpikesCharLink.lua
> +  elseif(event == 'CHARACTER_POINTS_CHANGED' or event == 'PLAYER_LOGOUT' or event == 'PLAYER_LEAVING_WORLD' or event == 'UNIT_INVENTORY_CHANGED') then
Leaving world event ist doch nicht mehr subscribed oder? Dann hier bitte auch aufräumen

2020-04-13 22:33 UTC, Spikeone commented on SpikesCharLink/SpikesCharLink.lua
> +        local strRebuiltItemstring = SCL_RebuildItemString("")
soltle wohl auch strRebuiltItemString lauten

2020-04-13 22:33 UTC, Spikeone commented on SpikesCharLink/SpikesCharLink.lua
> +    if(SCL_InspectLogedInAsText:GetText() ~= "") then
LoggedIn

2020-04-14 07:03 UTC, Zirafinu commented on SpikesCharLink/SpikesCharLink.lua
> +function StringToDecString(text)
ja die kann lokal

2020-04-14 07:04 UTC, Zirafinu commented on SpikesCharLink/SpikesCharLink.lua
> +            SendAddonMessage("SCLLV", SCL_CONSTS.VERSION, "WHISPER", wisperTarget);
ich hätte noch ganz viele ander tolle namen z.b. dataSource

2020-04-14 07:05 UTC, Zirafinu commented on SpikesCharLink/SpikesCharLink.lua
> +        local player, equipHash = SCL_SerializePlayer()
ich weiß nicht wie ich die werte gleich in die variablen aus dem äußeren scope schreibe

2020-04-14 07:06 UTC, Zirafinu commented on SpikesCharLink/SpikesCharLink.lua
> +  elseif(event == 'CHARACTER_POINTS_CHANGED' or event == 'PLAYER_LOGOUT' or event == 'PLAYER_LEAVING_WORLD' or event == 'UNIT_INVENTORY_CHANGED') then
done

2020-04-14 07:08 UTC, Zirafinu commented on SpikesCharLink/SpikesCharLink.lua
> +        local strRebuiltItemstring = SCL_RebuildItemString("")
habe ich nochmal etwas um gestrickt... anstatt den aufruf 2mal zu machen  check ich jetzt gleich ob der itemStrings[i] nil ist.

2020-04-14 07:08 UTC, Zirafinu commented on SpikesCharLink/SpikesCharLink.lua
> +    if(SCL_InspectLogedInAsText:GetText() ~= "") then
done

2020-04-14 07:10 UTC, Zirafinu commented on SpikesCharLink/SpikesCharLink.lua
> +      local characterName, appendString = SCL_ExtractCharacterNameFromParameter(arg2, 2, arg4);
Muss player name sein und nicht arg4

2020-04-14 07:12 UTC, Zirafinu commented
diue änderungen hab ich bei mir lokal schon gemacht ... wie bekomme ich die denn jetzt hier in den pull request rein

2020-04-14 09:31 UTC, Zirafinu reviewed
die anpassungen sind wieder auf dem Master ... ich weiß jetzt nicht ob ich noch einen pull request starten muss oder den hier approve?

2020-04-14 09:31 UTC, Zirafinu commented on SpikesCharLink/SpikesCharLink.lua
> +function StringToDecString(text)
sorry.
aber ich habe keine ahnung was ich hier tue

2020-04-14 12:27 UTC, Spikeone commented on SpikesCharLink/SpikesCharLink.lua
> +        local player, equipHash = SCL_SerializePlayer()
Kannst einfach nen _ machen, also z.b.

_, zweiterWert = FunktionMitMindestens2Returns

2020-04-14 12:28 UTC, Spikeone commented on SpikesCharLink/SpikesCharLink.lua
> +      local characterName, appendString = SCL_ExtractCharacterNameFromParameter(arg2, 2, arg4);
Versteh ich nicht aber wird schon passen :)

2020-04-14 12:29 UTC, Spikeone commented on SpikesCharLink/SpikesCharLink.lua
> +            SendAddonMessage("SCLLV", SCL_CONSTS.VERSION, "WHISPER", wisperTarget);
Weiß auch nicht genau was gemeint ist, außer, dass vermutlich viele Variablen nicht schön benannt sind^^

2020-04-14 12:30 UTC, Spikeone commented
So, sorry, ich habs vielleicht komplizierter gemacht als ich hätte sollen. Ich dachte nur, dass das Review feature ganz nett ist - zeigt mir direkt die änderungen an und ich bin ehrlich, ich hatte nicht so viel lust mir alle funktionen ganz genau anzusehen.

2020-04-14 12:30 UTC, Spikeone approved these changes

2020-04-14 12:31 UTC, merged

2020-04-14 21:04 UTC, Zirafinu commented
Also ich fands ganz interessant :-), hab ja auch noch nie was gemergt.
Das Review Feature wirkt schon sehr sinnvoll und ich glaube das, du das sehr richtig angewendet hast XD.
ich freue mich demnächst den ein, oder anderen twink link zu verschicken ^^